services:
  # --------------------------------------------
  # MOSQUITTO -----------------------------------
  # --------------------------------------------
  broker:
    env_file:
      - .env
    container_name: mosquitto-container
    hostname: mosquittoName
    image: eclipse-mosquitto
    ports:
      - "${MOSQUITTO_PORT}:1883"
    networks:
      - net-test
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  # --------------------------------------------
  # NODERED -----------------------------------
  # --------------------------------------------
  nodered:
    env_file:
      - .env
    container_name: nodered-container
    image: nodered/node-red:latest
    hostname: nodeName
    ports:
      - "${NODERED_PORT}:1880"
    networks:
      - net-test
    volumes:
      - ./nodered:/data
    depends_on:
      - broker


  # --------------------------------------------
  # INFLUXDB -----------------------------------
  # --------------------------------------------
  influxdb:
    env_file:
      - .env
    image: influxdb:2.1.1
    networks:
      - net-test
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    #env_file:
    # - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  # --------------------------------------------
  # GRAFANA -----------------------------------
  # --------------------------------------------
  grafana:
    env_file:
      - .env
    image: grafana/grafana-oss:8.4.3
    networks:
      - net-test
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      - ./grafana/provisioning:/etc/grafana/provisioning:ro    
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

  # --------------------------------------------
  # SENSORS -----------------------------------
  # --------------------------------------------
  sensors:
    build: ./sensors/
    hostname: sensorsName
    networks:
      - net-test
    depends_on:
      - broker
      - nodered

networks:
  net-test:
    driver: bridge

volumes:
  grafana-storage:
  influxdb-storage:
